import { NextPage } from "next";
import Head from "next/head";
import { View, StyleSheet } from "react-native";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View style={styles.container}>Testter</View>
    </div>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    position: "fixed",
  },
});
export default Home;
